# Generated by Django 3.1.3 on 2020-12-10 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0001_initial'),
        ('kit', '0002_kitlike_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_category',
            field=models.ManyToManyField(through='product.ProductDetailCategory', to='product.DetailCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='difficulty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.difficulty'),
        ),
        migrations.AddField(
            model_name='product',
            name='kit',
            field=models.ManyToManyField(through='product.ProductKit', to='kit.Kit'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.maincategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.signature'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.subcategory'),
        ),
        migrations.AddField(
            model_name='lecturevideo',
            name='lecture',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.lecture'),
        ),
        migrations.AddField(
            model_name='lectureprogress',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.lecture'),
        ),
        migrations.AddField(
            model_name='lectureprogress',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='lectureprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='lecturecontent',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.lecturecontentdescription'),
        ),
        migrations.AddField(
            model_name='lecturecontent',
            name='image_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.lecturecontentimageurl'),
        ),
        migrations.AddField(
            model_name='lecturecontent',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.lecture'),
        ),
        migrations.AddField(
            model_name='lecturecomment',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.lecture'),
        ),
        migrations.AddField(
            model_name='lecturecomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.lecturecomment'),
        ),
        migrations.AddField(
            model_name='lecturecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.chapter'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='communitylike',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.community'),
        ),
        migrations.AddField(
            model_name='communitylike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.community'),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='community',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='community',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
