# Generated by Django 3.1.3 on 2020-12-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201202_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='day',
        ),
        migrations.AddField(
            model_name='product',
            name='effective_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(max_length=20),
        ),
    ]
