# Generated by Django 3.1.3 on 2020-12-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201202_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='effective_time',
            field=models.DurationField(null=True),
        ),
    ]
