# Generated by Django 3.1.3 on 2020-12-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201202_1726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signiture',
            new_name='Signature',
        ),
        migrations.RenameField(
            model_name='lecturecontent',
            old_name='lecture_content_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='lecturecontent',
            old_name='lecture_content_image_url',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='signiture',
            new_name='signature',
        ),
        migrations.RenameField(
            model_name='productcontent',
            old_name='product_content_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productcontent',
            old_name='product_content_image_url',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='chapter',
            name='thumbnail_image',
            field=models.URLField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecturecomment',
            name='image_url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterModelTable(
            name='signature',
            table='signatures',
        ),
    ]
