# Generated by Django 3.1.3 on 2020-12-11 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('creator', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryproduct',
            name='difficulty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.difficulty'),
        ),
        migrations.AddField(
            model_name='temporaryproduct',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.maincategory'),
        ),
        migrations.AddField(
            model_name='temporaryproduct',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.subcategory'),
        ),
        migrations.AddField(
            model_name='temporaryproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='temporarylecturecontentimage',
            name='temporary_lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.temporarylecture'),
        ),
        migrations.AddField(
            model_name='temporarylecturecontentimage',
            name='temporary_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.temporaryproduct'),
        ),
        migrations.AddField(
            model_name='temporarylecturecontentdescription',
            name='temporary_lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.temporarylecture'),
        ),
        migrations.AddField(
            model_name='temporarylecturecontentdescription',
            name='temporary_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.temporaryproduct'),
        ),
        migrations.AddField(
            model_name='temporarylecturecontent',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='creator.temporarylecturecontentdescription'),
        ),
        migrations.AddField(
            model_name='temporarylecturecontent',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='creator.temporarylecturecontentimage'),
        ),
        migrations.AddField(
            model_name='temporarylecturecontent',
            name='temporary_lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.temporarylecture'),
        ),
        migrations.AddField(
            model_name='temporarylecturecontent',
            name='temporary_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.temporaryproduct'),
        ),
        migrations.AddField(
            model_name='temporarylecture',
            name='temporary_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.temporarychapter'),
        ),
        migrations.AddField(
            model_name='temporarylecture',
            name='temporary_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.temporaryproduct'),
        ),
        migrations.AddField(
            model_name='temporarykitimage',
            name='temporary_kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.temporarykit'),
        ),
        migrations.AddField(
            model_name='temporarykitimage',
            name='temporary_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.temporaryproduct'),
        ),
        migrations.AddField(
            model_name='temporarykit',
            name='temporary_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.temporaryproduct'),
        ),
        migrations.AddField(
            model_name='temporarychapter',
            name='temporary_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.temporaryproduct'),
        ),
    ]
