<<<<<<< HEAD
# Generated by Django 3.1.3 on 2020-12-02 13:56
=======
# Generated by Django 3.1.3 on 2020-12-04 10:00
>>>>>>> 3a472ce... Add: SignUpView

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kit', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
