# Generated by Django 3.1.3 on 2020-12-09 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('kit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
