# Generated by Django 3.1.3 on 2020-12-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201202_1628'),
        ('kit', '0002_kitlike_user'),
        ('user', '0002_communitycommentlike_productlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='kit_free_flag',
            new_name='is_kit_free',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='benefit_flag',
            new_name='is_benefit',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='creator_flag',
            new_name='is_creator',
        ),
        migrations.RemoveField(
            model_name='userproduct',
            name='expire_date',
        ),
        migrations.AddField(
            model_name='user',
            name='community_comment_like',
            field=models.ManyToManyField(related_name='comment_like_user', through='user.CommunityCommentLike', to='product.CommunityComment'),
        ),
        migrations.AddField(
            model_name='user',
            name='community_like',
            field=models.ManyToManyField(related_name='community_like_user', through='product.CommunityLike', to='product.Community'),
        ),
        migrations.AddField(
            model_name='user',
            name='kit_like',
            field=models.ManyToManyField(through='kit.KitLike', to='kit.Kit'),
        ),
        migrations.AddField(
            model_name='user',
            name='product_like',
            field=models.ManyToManyField(related_name='product_like_user', through='user.ProductLike', to='product.Product'),
        ),
        migrations.AddField(
            model_name='user',
            name='recently_view',
            field=models.ManyToManyField(related_name='product_view_user', through='user.RecentlyView', to='product.Product'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_product',
            field=models.ManyToManyField(related_name='product_buy_user', through='user.UserProduct', to='product.Product'),
        ),
        migrations.AlterModelTable(
            name='communitycommentlike',
            table='community_comment_likes',
        ),
        migrations.AlterModelTable(
            name='productlike',
            table='product_likes',
        ),
    ]
